// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: geo/v1/geo.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GEOClient is the client API for GEO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GEOClient interface {
	Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationReply, error)
}

type gEOClient struct {
	cc grpc.ClientConnInterface
}

func NewGEOClient(cc grpc.ClientConnInterface) GEOClient {
	return &gEOClient{cc}
}

func (c *gEOClient) Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationReply, error) {
	out := new(LocationReply)
	err := c.cc.Invoke(ctx, "/api.geo.v1.GEO/Location", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GEOServer is the server API for GEO service.
// All implementations must embed UnimplementedGEOServer
// for forward compatibility
type GEOServer interface {
	Location(context.Context, *LocationRequest) (*LocationReply, error)
	mustEmbedUnimplementedGEOServer()
}

// UnimplementedGEOServer must be embedded to have forward compatible implementations.
type UnimplementedGEOServer struct {
}

func (UnimplementedGEOServer) Location(context.Context, *LocationRequest) (*LocationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Location not implemented")
}
func (UnimplementedGEOServer) mustEmbedUnimplementedGEOServer() {}

// UnsafeGEOServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GEOServer will
// result in compilation errors.
type UnsafeGEOServer interface {
	mustEmbedUnimplementedGEOServer()
}

func RegisterGEOServer(s grpc.ServiceRegistrar, srv GEOServer) {
	s.RegisterService(&GEO_ServiceDesc, srv)
}

func _GEO_Location_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GEOServer).Location(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.geo.v1.GEO/Location",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GEOServer).Location(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GEO_ServiceDesc is the grpc.ServiceDesc for GEO service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GEO_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.geo.v1.GEO",
	HandlerType: (*GEOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Location",
			Handler:    _GEO_Location_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geo/v1/geo.proto",
}
